### ISSUE TITLE
Archivo de World - EntregaPDS#2

### ISSUE THREAD

**Issue by JuanmaZapataOlaya** [JuanmaZapataOlaya/Conteo-de-Parqueaderos-Eafit#21]
Realizar y juntar todos los puntos de la EntregaPDS#2 en un mismo archivo y ASEGURARSE de que todo funciona y no falte nada.

Tiempo aprox: 20Min

**Comment by cadasaso** [comment]
[PDS.cdsanchezs.Entrega2..docx](https://github.com/JuanmaZapataOlaya/Conteo-de-Parqueaderos-Eafit/files/11106523/PDS.cdsanchezs.Entrega2.docx)
