### ISSUE TITLE
Realizar Sustentación

### ISSUE THREAD

**Issue by JuanmaZapataOlaya** [JuanmaZapataOlaya/Conteo-de-Parqueaderos-Eafit#53]

**Comment by masalgaro** [comment]
[PARQUEA EAFIT Sustentacion.pptx](https://github.com/JuanmaZapataOlaya/Conteo-de-Parqueaderos-Eafit/files/11482729/PARQUEA.EAFIT.Sustentacion.pptx)

La presentación cubre todo lo básico de la sustentación, tristemente creo que la música de fondo no dura 7 minutos seguidos de exposición, pero al menos es un buen detalle

**Comment by masalgaro** [comment]
Se me olvidó poner decoración en 3 diapositivas wow

[PARQUEA EAFIT Sustentacion.pptx](https://github.com/JuanmaZapataOlaya/Conteo-de-Parqueaderos-Eafit/files/11488353/PARQUEA.EAFIT.Sustentacion.pptx)

Veamos si no hay errores por subir 2 veces el mismo pptx
