### ISSUE TITLE
Punto #1 Requisitos

### ISSUE THREAD

**Issue by JuanmaZapataOlaya** [JuanmaZapataOlaya/Conteo-de-Parqueaderos-Eafit#54]
< Indique los requisitos con los que cumplirá cada módulo de su sistema. NOTA: Considere las recomendaciones recibidas en la Entrega 2 >

**Comment by masalgaro** [comment]
[Requisitos Entrega 3.docx](https://github.com/JuanmaZapataOlaya/Conteo-de-Parqueaderos-Eafit/files/11240845/Requisitos.Entrega.3.docx)

Mismo archivo que he estado subiendo en el chat de Teams, solo que aquí de una vez para cerrar el issue

**Comment by masalgaro** [comment]
[Requisitos Entrega 3.docx](https://github.com/JuanmaZapataOlaya/Conteo-de-Parqueaderos-Eafit/files/11251571/Requisitos.Entrega.3.docx)

Ya terminados los requisitos, aquí están los requisitos funcionales y no funcionales, que previamente se han enviado al chat de Teams

**Comment by masalgaro** [comment]
[Requisitos Entrega 3.docx](https://github.com/JuanmaZapataOlaya/Conteo-de-Parqueaderos-Eafit/files/11279248/Requisitos.Entrega.3.docx)

Requisitos actualizados para acomodar los nuevos tipos de celda
