### ISSUE TITLE
Punto #3 Diagrama de clases

### ISSUE THREAD

**Issue by JuanmaZapataOlaya** [JuanmaZapataOlaya/Conteo-de-Parqueaderos-Eafit#56]
< Presente el diagrama de clases de su proyecto. Recuerde incluir mínimo una clase por cada módulo. El diagrama debe estar elaborado en la herramienta GenMyModel. Adjunte la imagen y el enlace.>

**Comment by cadasaso** [comment]
[src.zip](https://github.com/JuanmaZapataOlaya/Conteo-de-Parqueaderos-Eafit/files/11300078/src.zip)

**Comment by cadasaso** [comment]
![Image](https://user-images.githubusercontent.com/124532894/233759335-0b6f7894-9979-48cc-a5f6-f161b126c775.png)

**Comment by cadasaso** [comment]
https://app.genmymodel.com/api/projects/_5LSTENzJEe2JhIahQQsnAA/diagrams/_5LS6ItzJEe2JhIahQQsnAA/svg
