### ISSUE TITLE
Punto #6 Video

### ISSUE THREAD

**Issue by JuanmaZapataOlaya** [JuanmaZapataOlaya/Conteo-de-Parqueaderos-Eafit#59]
Planeación y organización del video

**Comment by masalgaro** [comment]
El vídeo es muy grande para subir directamente en este comentario, _pero_ puedo intentar subirlo a YouTube en privado y montar el link en un momento

**Comment by masalgaro** [comment]
https://youtu.be/GuIWcypS02s

Si esto funciona, oficialmente el vídeo ya está terminado y fácilmente accesible
